export type TooltipSaveScope = 'none' | 'local-project' | 'linked-workbook' | 'export-only';

export type TooltipContext = {
  disabled?: boolean;
  disabledReason?: string;
  cellAddress?: string;
  protectedReason?: string;
};

export type TooltipDefinition = {
  title: string;
  body: string;
  saveScope?: TooltipSaveScope;
  disabledReason?: string | ((context: TooltipContext) => string);
  shortcut?: string;
};

const t = (
  title: string,
  body: string,
  saveScope: TooltipSaveScope = 'none',
  extra: Pick<TooltipDefinition, 'disabledReason' | 'shortcut'> = {},
): TooltipDefinition => ({ title, body, saveScope, ...extra });

export const tooltipRegistry = {
  'project.new': t('New project', 'Creates a new local Singh360 project. It does not create or modify an Excel workbook until one is linked and Save + Write Excel is used.', 'local-project'),
  'project.open': t('Open project', 'Opens the selected local Singh360 project package and its saved editor state.'),
  'project.importWorkbook': t('Import workbook', 'Creates or refreshes a Singh360 project from a selected workbook using the controlled import workflow. The source workbook must not be edited at the same time.', 'local-project'),
  'project.recentCard': t('Recent project', 'Opens this project. The card status describes local-save and workbook-link state.'),
  'project.openFolder': t('Open project folder', 'Opens the local project package folder in File Explorer. This does not save or sync anything.'),
  'project.linkWorkbook': t('Link workbook', 'Associates this Singh360 project with an Excel workbook. Linking does not write to the workbook.', 'local-project'),
  'project.relinkWorkbook': t('Change linked workbook', 'Selects a different workbook link. Verify that the selected workbook belongs to this project before continuing.', 'local-project'),
  'project.refreshWorkbook': t('Refresh from workbook', 'Reads eligible workbook changes into the project only when conflict rules allow it. It does not bypass two-sided conflict protection.', 'local-project'),
  'project.backup': t('Back up project', 'Creates a recoverable project-package backup before risky work.', 'export-only'),
  'project.delete': t('Remove project', 'Removes the selected local project only after confirmation. It must not silently delete the linked workbook.', 'local-project'),
  'project.status.noWorkbook': t('No workbook linked', 'The project can be edited locally, but Save + Write Excel is unavailable until a workbook is linked.'),
  'project.status.linked': t('Workbook linked', 'This project has a linked workbook. Linking alone does not mean the workbook is synchronized.'),
  'project.status.syncPending': t('Workbook sync pending', 'The local project contains confirmed saved changes that have not yet been mirrored to the linked workbook.'),
  'project.status.conflict': t('Project/workbook conflict', 'Both the local project and workbook changed since the last confirmed sync. Do not overwrite either side until the conflict workflow resolves it.'),

  'nav.projectHome': t('Project Home', 'Returns to the project dashboard. Unsaved local edits must be saved or explicitly handled before leaving.'),
  'nav.pageManager': t('Visual Page Manager', 'Opens the full-screen page organizer for inclusion, order, page codes, titles, and page actions.'),
  'nav.componentLibrary': t('Component Library', 'Opens reusable symbols, components, plan markers, callouts, safety signs, and saved legends.'),
  'nav.symbolMapper': t('Symbol Mapper', 'Finds supported symbols on an existing drawing and applies the approved map highlights.'),
  'nav.help': t('Help', 'Opens application guidance. Tooltips remain available while help is open.'),
  'status.localSaved': t('Project saved', 'The current project state is confirmed saved locally. This does not prove the linked workbook is current.'),
  'status.unsavedProject': t('Unsaved project edits', 'One or more project edits have not yet been confirmed saved locally. Open What is unsaved? for details.'),
  'status.unsavedWorkspace': t('Unsaved workspace edits', 'Data Workspace changes exist in memory and are not yet confirmed saved to the local Singh360 project.'),
  'status.syncPending': t('Workbook sync pending', 'The project is locally saved, but the linked workbook still needs Save + Write Excel.'),
  'status.conflict': t('Project/workbook conflict', 'Both sides changed. Automatic overwrite is blocked to protect data.'),
  'status.whatUnsaved': t('What is unsaved?', 'Lists the actual dirty areas currently waiting for local save.'),
  'status.lastLocalSave': t('Last local save', 'Shows when the project was last confirmed saved to the local Singh360 package.'),
  'status.lastWorkbookSync': t('Last workbook sync', 'Shows when Save + Write Excel last completed successfully.'),

  'save.localProject': t('Save project', 'Saves current editor and Data Workspace changes to the local Singh360 project. It does not write the linked Excel workbook.', 'local-project', { shortcut: 'Ctrl+S' }),
  'save.workspace': t('Save workspace edits', 'Saves Data Workspace cell and structure changes into the local Singh360 project. The unsaved marker clears only after confirmation.', 'local-project'),
  'save.writeExcel': t('Save + Write Excel', 'Saves the local project first, then mirrors controlled workbook data, 00_INDEX, tabs, order, codes, titles, inclusion, status colors, and workbook-backed page data to the linked workbook. Close Excel before running it.', 'linked-workbook'),
  'save.autosave': t('Local autosave', 'Singh360 periodically saves the local project. Workbook sync remains explicit.', 'local-project'),
  'save.retry': t('Retry save', 'Retries the failed local save without discarding current edits.', 'local-project'),
  'save.resolveConflict': t('Resolve conflict', 'Opens the protected conflict workflow. It must not force an overwrite.'),
  'workbook.copyPath': t('Copy generated workbook path', 'Copies the exact generated workbook path without opening or changing the workbook.'),
  'assembly.saveSelection': t('Save selection as assembly', 'Stores the selected group as a reusable project assembly. Its parts remain editable after insertion.', 'local-project'),
  'assembly.signage-marker-trio': t('Signage Marker Trio', 'Inserts the three standard signage markers as one editable persistent group.', 'local-project'),
  'assembly.signage-legend': t('Signage Legend', 'Inserts a framed editable legend for the standard signage markers.', 'local-project'),
  'assembly.callout-block': t('Callout Block', 'Inserts an editable callout number, note, and leader as a movable group.', 'local-project'),
  'assembly.generated-symbol-key': t('Generated Symbol Key', 'Builds an editable key from component symbols currently used on the active page.', 'local-project'),
  'assembly.wicp-annotation-pack': t('WICP Annotation Pack', 'Inserts the standard WICP title, note, and leader annotation group.', 'local-project'),
  'export.pdf': t('Export PDF', 'Creates a PDF drawing package from included published pages. It does not modify the workbook.', 'export-only'),
  'export.projectPackage': t('Export project package', 'Creates a portable Singh360 project package containing the project state and approved assets.', 'export-only'),
  'export.worksheet': t('Export worksheet', 'Creates a standalone worksheet export from the current app-managed page without changing the linked workbook.', 'export-only'),

  'pages.search': t('Search pages', 'Filters the page list by code, title, tab, family, type, or status.'),
  'pages.filter': t('Filter pages', 'Shows only pages matching the selected inclusion, status, family, or type filter.'),
  'pages.clearFilter': t('Clear page filters', 'Returns the sidebar to all available pages.'),
  'pages.pagePill': t('Published page number', 'Shows the page’s published position among included drawing pages. Excluded pages do not count.'),
  'pages.active': t('Active page', 'This is the page currently shown in the editor.'),
  'pages.include': t('Include in drawing', 'Controls whether this base page publishes. Only explicit Include/Yes/True rows publish.', 'local-project'),
  'pages.exclude': t('Exclude from drawing', 'Keeps the source/reference page available but removes it from the published package.', 'local-project'),
  'pages.dragReorder': t('Reorder page', 'Drag to change base-page order. Cover remains first and Sheet Index/TOC remains second.', 'local-project'),
  'pages.previous': t('Previous page', 'Opens the previous page that matches the current filter.'),
  'pages.next': t('Next page', 'Opens the next page that matches the current filter.'),
  'pages.moreActions': t('Page actions', 'Opens rename, duplicate, include/exclude, type, status, and delete actions available for this page.'),
  'pages.duplicate': t('Duplicate page', 'Creates a new base page from this page while preserving the original.', 'local-project'),
  'pages.delete': t('Delete app page', 'Deletes only after confirmation and must preserve protected source/reference behavior.', 'local-project'),
  'pages.rename': t('Rename page', 'Changes the app page title and, when mirrored, the controlled workbook title fields.', 'local-project'),
  'pages.sheetCode': t('Sheet code', 'The drawing-package code controlled by 00_INDEX for a base page.', 'local-project'),
  'pages.sheetTab': t('Worksheet tab', 'The workbook worksheet name linked to this base page.'),

  'view.normalized': t('Normalized view', 'Shows the Singh360 page rendering produced from structured project data.'),
  'view.source': t('Source view', 'Shows the preserved source worksheet/page representation for comparison.'),
  'view.canvas': t('Canvas view', 'Opens the editable drawing-object canvas for manual layouts and overlays.'),
  'view.excelLayout': t('Excel Layout', 'Places independent editable tables on a real 11 × 17 canvas and exports them as real Excel cells.'),
  'view.fitWidth': t('Fit width', 'Fits the active page width in the available editor area.'),
  'view.fitPage': t('Fit page', 'Fits the entire 11 × 17 page in the editor.'),
  'view.zoom100': t('Actual size', 'Displays the page at 100% editor zoom.'),
  'view.zoomIn': t('Zoom in', 'Magnifies the editor view without changing exported dimensions.'),
  'view.zoomOut': t('Zoom out', 'Reduces the editor view without changing exported dimensions.'),
  'view.printBoundary': t('Printable boundary', 'The dotted line marks the area intended to remain inside the printed 11 × 17 page.'),
  'view.continuationPage': t('Continuation page', 'This page is generated from overflow. It must not create a duplicate base row in 00_INDEX.'),
  'view.printMode': t('Print preview', 'Hides editing chrome and previews the published page output.'),

  'edit.undo': t('Undo', 'Reverses the most recent supported editor action.', 'local-project', { shortcut: 'Ctrl+Z' }),
  'edit.redo': t('Redo', 'Restores the most recently undone action.', 'local-project', { shortcut: 'Ctrl+Y' }),
  'edit.cut': t('Cut', 'Removes the selected editable item and places it on the clipboard.', 'local-project', { shortcut: 'Ctrl+X' }),
  'edit.copy': t('Copy', 'Copies the selected item without removing it.', 'none', { shortcut: 'Ctrl+C' }),
  'edit.paste': t('Paste', 'Pastes supported clipboard content. Excel, HTML, CSV, and TSV tables must remain editable tables where supported.', 'local-project', { shortcut: 'Ctrl+V' }),
  'edit.duplicate': t('Duplicate', 'Creates a movable copy of the selected object or table.', 'local-project', { shortcut: 'Ctrl+D' }),
  'edit.delete': t('Delete selection', 'Removes the selected editable object after applying current confirmation rules.', 'local-project', { shortcut: 'Delete' }),
  'insert.text': t('Insert text', 'Adds an editable text object to the current page.', 'local-project'),
  'insert.table': t('Insert table', 'Adds a real editable table, not a screenshot or flat text note.', 'local-project'),
  'insert.image': t('Insert image', 'Adds an image object that can be moved, resized, bordered, shadowed, and saved with the project.', 'local-project'),
  'insert.pdfCrop': t('Insert PDF crop', 'Opens the precision crop tool and inserts the selected PDF region as a movable page object.', 'local-project'),
  'insert.component': t('Insert component', 'Opens the Component Library for direct insertion of a reusable component.', 'local-project'),
  'insert.symbolLegend': t('Insert symbol legend', 'Builds or inserts an editable saved legend using approved component assets.', 'local-project'),
  'insert.connector': t('Insert connector', 'Adds a line or connector between drawing objects.', 'local-project'),
  'insert.callout': t('Insert callout', 'Adds a numbered or labeled callout object.', 'local-project'),
  'arrange.front': t('Bring to front', 'Moves the selected object above all overlapping objects.', 'local-project'),
  'arrange.forward': t('Bring forward', 'Moves the selected object one layer upward.', 'local-project'),
  'arrange.backward': t('Send backward', 'Moves the selected object one layer downward.', 'local-project'),
  'arrange.back': t('Send to back', 'Moves the selected object behind all overlapping objects.', 'local-project'),
  'arrange.alignLeft': t('Align left', 'Aligns selected objects to a common left edge.', 'local-project'),
  'arrange.alignCenter': t('Align centers', 'Aligns selected objects to a common horizontal center.', 'local-project'),
  'arrange.alignRight': t('Align right', 'Aligns selected objects to a common right edge.', 'local-project'),
  'arrange.alignTop': t('Align top', 'Aligns selected objects to a common top edge.', 'local-project'),
  'arrange.alignMiddle': t('Align middles', 'Aligns selected objects to a common vertical center.', 'local-project'),
  'arrange.alignBottom': t('Align bottom', 'Aligns selected objects to a common bottom edge.', 'local-project'),
  'arrange.distributeHorizontal': t('Distribute horizontally', 'Spaces selected objects evenly from left to right.', 'local-project'),
  'arrange.distributeVertical': t('Distribute vertically', 'Spaces selected objects evenly from top to bottom.', 'local-project'),
  'arrange.snap': t('Snap', 'Snaps movement and resizing to supported page, grid, and object guides.'),
  'arrange.guides': t('Alignment guides', 'Shows temporary PowerPoint-style guides while moving or resizing objects.'),

  'object.select': t('Select object', 'Click to select. Drag to move. Use handles to resize or rotate when supported.'),
  'object.lock': t('Lock object', 'Prevents accidental movement or resizing while keeping the object visible.', 'local-project'),
  'object.positionX': t('Horizontal position', 'Sets the object’s left position on the 11 × 17 page.', 'local-project'),
  'object.positionY': t('Vertical position', 'Sets the object’s top position on the 11 × 17 page.', 'local-project'),
  'object.width': t('Object width', 'Changes the selected object’s width.', 'local-project'),
  'object.height': t('Object height', 'Changes the selected object’s height.', 'local-project'),
  'object.rotation': t('Rotation', 'Rotates the selected object by the specified angle.', 'local-project'),
  'object.opacity': t('Opacity', 'Changes object transparency without changing the source asset.', 'local-project'),
  'object.border': t('Border', 'Adds or changes the visible border around the selected image or PDF crop.', 'local-project'),
  'object.borderWidth': t('Border width', 'Sets the selected object’s border thickness.', 'local-project'),
  'object.borderColor': t('Border color', 'Sets the selected object’s border color.', 'local-project'),
  'object.shadow': t('Shadow', 'Adds or removes a drop shadow from the selected image or PDF crop.', 'local-project'),
  'object.shadowBlur': t('Shadow blur', 'Controls how soft the object shadow appears.', 'local-project'),
  'object.shadowOffset': t('Shadow offset', 'Controls how far the shadow moves from the object.', 'local-project'),
  'object.crop': t('Edit crop', 'Reopens crop controls for the selected supported image or PDF crop.', 'local-project'),
  'object.group': t('Group', 'Treats selected objects as one movable unit while preserving their contents.', 'local-project'),
  'object.ungroup': t('Ungroup', 'Returns a group to independently editable objects.', 'local-project'),

  'workspace.open': t('Data Workspace', 'Opens workbook-backed page data for structured editing inside Singh360.'),
  'workspace.sheetSelector': t('Workspace sheet', 'Selects the page or worksheet data being edited. Switching views does not automatically write Excel.'),
  'workspace.cell': t('Workspace cell', 'Click to select this cell. Editing changes the local workspace state until Save Workspace Edits confirms a local save.', 'local-project'),
  'workspace.cellAddress': t('Cell address', 'Shows the selected worksheet-style row and column reference.'),
  'workspace.formulaBar': t('Cell value editor', 'Edits the selected cell value or formula text supported by the workspace model.', 'local-project'),
  'workspace.addRow': t('Add row', 'Inserts a row in the app-managed workspace data. Save locally before leaving.', 'local-project'),
  'workspace.deleteRow': t('Delete row', 'Removes the selected app-managed row after confirmation.', 'local-project'),
  'workspace.addColumn': t('Add column', 'Inserts a column in the app-managed workspace data.', 'local-project'),
  'workspace.deleteColumn': t('Delete column', 'Removes the selected app-managed column after confirmation.', 'local-project'),
  'workspace.merge': t('Merge cells', 'Combines the selected valid cell range into one displayed cell.', 'local-project'),
  'workspace.unmerge': t('Unmerge cells', 'Separates the selected merged range into individual cells.', 'local-project'),
  'workspace.wrap': t('Wrap text', 'Displays long text on multiple lines inside the selected cell or range.', 'local-project'),
  'workspace.bold': t('Bold', 'Toggles bold formatting for the selected editable cell or range.', 'local-project'),
  'workspace.italic': t('Italic', 'Toggles italic formatting for the selected editable cell or range.', 'local-project'),
  'workspace.underline': t('Underline', 'Toggles underline formatting for the selected editable cell or range.', 'local-project'),
  'workspace.fill': t('Cell fill', 'Changes the selected cell or range background fill.', 'local-project'),
  'workspace.fontColor': t('Font color', 'Changes text color in the selected cell or range.', 'local-project'),
  'workspace.border': t('Cell borders', 'Changes border placement and style for the selected cell or range.', 'local-project'),
  'workspace.rowHeight': t('Row height', 'Changes the selected app-managed row height.', 'local-project'),
  'workspace.columnWidth': t('Column width', 'Changes the selected app-managed column width.', 'local-project'),
  'workspace.pasteTable': t('Paste table', 'Pastes Excel, HTML, CSV, or TSV cells as structured editable workspace cells.', 'local-project'),
  'workspace.reload': t('Reload saved workspace', 'Reloads the last confirmed local project state. Warn before replacing genuine unsaved edits.'),
  'workspace.discard': t('Discard workspace edits', 'Reverts only genuine unconfirmed Data Workspace edits after explicit confirmation.'),
  'workspace.save': t('Save workspace edits', 'Saves current workspace edits into the local Singh360 project. It does not write the linked workbook.', 'local-project'),
  'workspace.syncExcel': t('Save + Write Excel', 'Saves locally first, then mirrors approved workbook-backed changes through the protected full workbook workflow.', 'linked-workbook'),
  'workspace.unsavedBadge': t('Unsaved workspace edits', 'This badge remains until the current workspace revision is confirmed saved locally.'),
  'workspace.savedBadge': t('Workspace saved', 'The current workspace revision is confirmed saved in the local Singh360 project.'),
  'workspace.sourceRange': t('Source range', 'Shows the preserved workbook range associated with this workspace region when available.'),
  'workspace.protectedCell': t('Protected source cell', 'This source-backed cell cannot be changed through the current workspace action. The tooltip states the actual reason.'),

  'excelLayout.enable': t('Enable Excel Layout', 'Converts or enables this app page for independent editable table placement on the 11 × 17 canvas.', 'local-project'),
  'excelLayout.addTable': t('Add table', 'Adds a new independently sized and positioned editable table.', 'local-project'),
  'excelLayout.pasteTable': t('Paste table', 'Creates a new editable table from Excel, HTML, CSV, or TSV clipboard data.', 'local-project'),
  'excelLayout.table': t('Excel Layout table', 'This table has its own position, dimensions, columns, rows, merges, title, styles, and overflow behavior.'),
  'excelLayout.tableTitle': t('Table title', 'Sets the first-class merged title printed above this table. It is not a fake body row.', 'local-project'),
  'excelLayout.mergeTitle': t('Merge title across table', 'Merges the exported Excel title cell across this table’s visible width.', 'local-project'),
  'excelLayout.columnWidth': t('Table column width', 'Resizes this table’s column only. It must not change an unrelated table above or below it.', 'local-project'),
  'excelLayout.rowHeight': t('Table row height', 'Changes the selected row height and exported editable-cell geometry.', 'local-project'),
  'excelLayout.keepTogether': t('Keep together', 'Moves the table to the next 11 × 17 page when it fits there as one unit.', 'local-project'),
  'excelLayout.splitRows': t('Split rows', 'Allows overflow to continue on later pages, splitting only at valid row boundaries.', 'local-project'),
  'excelLayout.repeatTitle': t('Repeat table title', 'Repeats the merged table title on continuation pages.', 'local-project'),
  'excelLayout.repeatHeaders': t('Repeat column headers', 'Repeats the table’s column header row on continuation pages.', 'local-project'),
  'excelLayout.tabColor': t('Workbook tab color', 'Sets the custom worksheet tab color for this included page. Excluded-page gray still overrides it.', 'local-project'),
  'excelLayout.pageBoundary': t('11 × 17 page boundary', 'Marks one Tabloid landscape page. Moving content below it creates a continuation page.'),
  'excelLayout.printableBoundary': t('Printable area', 'Keep critical content inside this dotted boundary to avoid printer clipping.'),
  'excelLayout.continuationIdentity': t('Continuation identity', 'Shows the generated continuation segment. It does not create a duplicate 00_INDEX base row.'),

  'pageManager.open': t('Visual Page Manager', 'Opens the full-screen page organizer.'),
  'pageManager.tile': t('Page tile', 'Selects this page and shows its current include, code, title, type, and status.'),
  'pageManager.drag': t('Reorder page', 'Drag the tile to change base-page order. Protected Cover and Sheet Index positions remain enforced.', 'local-project'),
  'pageManager.include': t('Publish this page', 'Includes the base page in the drawing package and published page numbering.', 'local-project'),
  'pageManager.exclude': t('Keep as source/reference', 'Keeps the page available but removes it from published page numbering and output.', 'local-project'),
  'pageManager.autoScroll': t('Active-page tracking', 'Automatically scrolls the manager so the active page tile remains visible.'),
  'pageManager.save': t('Save page changes', 'Saves page order and metadata to the local project. Workbook mirroring remains explicit.', 'local-project'),
  'pageManager.close': t('Close Page Manager', 'Returns to the editor. Warn only when genuine unsaved page-manager edits remain.'),

  'pdfCrop.source': t('PDF source', 'Selects the source PDF and page used for this crop.'),
  'pdfCrop.page': t('PDF page', 'Changes the source PDF page without changing the crop already saved until Apply is used.'),
  'pdfCrop.zoom': t('Crop zoom', 'Magnifies the source view for precise selection. It does not change output resolution by itself.'),
  'pdfCrop.pan': t('Pan source', 'Moves the PDF beneath the crop viewport without changing the selected dimensions.'),
  'pdfCrop.rotateLeft': t('Rotate left', 'Rotates the crop 90° counterclockwise.', 'local-project'),
  'pdfCrop.rotateRight': t('Rotate right', 'Rotates the crop 90° clockwise.', 'local-project'),
  'pdfCrop.exactWidth': t('Exact crop width', 'Sets the crop width using the supported page measurement system.', 'local-project'),
  'pdfCrop.exactHeight': t('Exact crop height', 'Sets the crop height using the supported page measurement system.', 'local-project'),
  'pdfCrop.highDpi': t('High-resolution crop', 'Creates the inserted crop at high enough resolution for drawing-package output.', 'local-project'),
  'pdfCrop.apply': t('Insert crop', 'Inserts the selected crop as a separate movable canvas object and saves it with the project after local save.', 'local-project'),
  'pdfCrop.cancel': t('Cancel crop', 'Closes the crop tool without inserting the pending crop.'),

  'library.search': t('Search components', 'Filters the Component Library by name, code, category, collection, alias, or description.'),
  'library.collection': t('Component collection', 'Shows only components in the selected saved collection.'),
  'library.category': t('Component category', 'Filters components by category without changing the saved component.'),
  'library.card': t('Component card', 'Shows the saved reusable component. Use Direct Insert to place a separate movable object.'),
  'library.directInsert': t('Direct insert', 'Places this exact saved component on the active page as a separate movable object.', 'local-project'),
  'library.favorite': t('Favorite', 'Adds or removes this component from favorites without changing the source asset.', 'local-project'),
  'library.edit': t('Edit component', 'Opens supported metadata or reusable-object editing. It must not silently alter existing placed copies.', 'local-project'),
  'library.delete': t('Delete saved component', 'Removes the saved library entry only after confirmation. It must not remove existing placed objects.', 'local-project'),
  'library.saveLegend': t('Save legend', 'Saves the current editable legend as a reusable Component Library entry.', 'local-project'),
  'legend.builder': t('Symbol Legend builder', 'Builds an editable legend from selected approved symbols.'),
  'legend.row': t('Legend row', 'Represents one symbol and its verified description.'),
  'legend.insertSeparate': t('Insert selected symbols separately', 'Inserts each selected legend symbol as an independent movable object.', 'local-project'),
  'symbolMapper.scan': t('Scan page symbols', 'Searches the active source drawing for supported symbol occurrences.'),
  'symbolMapper.include': t('Include match', 'Marks this verified occurrence for approved map highlighting.', 'local-project'),
  'symbolMapper.ignore': t('Ignore match', 'Excludes this occurrence from generated highlights without deleting source content.', 'local-project'),
  'symbolMapper.apply': t('Apply highlights', 'Places approved component highlights on included verified occurrences.', 'local-project'),

  'recovery.openBackup': t('Open backup', 'Opens a selected project backup for inspection or controlled recovery.'),
  'recovery.restore': t('Restore backup', 'Restores the selected backup only after showing the exact target and required confirmation.', 'local-project'),
  'recovery.cancel': t('Cancel recovery', 'Closes recovery without changing project data.'),
  'workspaceCleanup.open': t('Workspace cleanup', 'Opens the existing cleanup workflow. The preview names what it can archive and what it preserves.'),
  'workspaceCleanup.preview': t('Preview cleanup', 'Shows proposed cleanup actions before any change.'),
  'workspaceCleanup.confirm': t('Confirm cleanup', 'Executes only the previewed cleanup after protected backup and confirmation.', 'local-project'),
  'dialog.confirm': t('Confirm action', 'Executes the action described in this dialog.'),
  'dialog.cancel': t('Cancel', 'Closes the dialog without applying the pending action.'),
  'dialog.close': t('Close dialog', 'Closes this window. Warn only if genuine unsaved dialog edits would be lost.'),
  'warning.disabled': t('Command unavailable', 'This command is unavailable until its required selection, project, or linked resource is ready.', 'none', {
    disabledReason: (context) => context.disabledReason || 'Complete the prerequisite shown by this control, then try again.',
  }),

  'control.action': t('Application action', 'Runs the named Singh360 action. The control label describes the result; no data is changed until the action is used.'),
  'control.input': t('Editable field', 'Changes the named local project field. The change is confirmed only after local project save.', 'local-project'),
  'control.select': t('Choose an option', 'Changes the selected local editor option. Workbook mirroring remains explicit.', 'local-project'),
  'control.toggle': t('Toggle setting', 'Turns the named editor option on or off.'),
  'control.status': t('Status', 'Shows the current application state.'),
  'control.tab': t('Application tab', 'Opens the named group of application controls.'),
  'control.drag': t('Drag control', 'Drag to reposition or reorder the supported item.', 'local-project'),
} satisfies Record<string, TooltipDefinition>;

export type TooltipHelpId = keyof typeof tooltipRegistry;

export function getTooltipDefinition(helpId: string): TooltipDefinition | undefined {
  return tooltipRegistry[helpId as TooltipHelpId];
}

export function tooltipScopeLabel(scope: TooltipSaveScope | undefined): string {
  if (scope === 'local-project') return 'Saves to: local Singh360 project';
  if (scope === 'linked-workbook') return 'Writes: linked Excel workbook';
  if (scope === 'export-only') return 'Creates: exported file only';
  return 'Changes: none';
}
